server:
  port: 8081
spring:
  application:
    name: medApp
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      javax.persistence.schema-generation.database.action: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false