spring:
  web:
    locale: en
    locale-resolver: fixed
  application:
    name: medApp
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql
      mode: always


urlbase: http://localhost:8081
